name: Update WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false

          LANG_COUNT: 6

          TIME_RANGE: last_7_days

          BLOCKS: █▓▒░

          CODE_LANG: text

          COMMIT_MESSAGE: "Updated WakaTime stats"
