name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          SHOW_TIME: true
          SHOW_TOTAL: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 6
          BLOCKS: █▓▒░
          CODE_LANG: text
